Repository sayannath/Libaray-Management-System-Flutter, pull requests merged in 2020-10, with the labels that each got.

#17 Revert "Added toast matter for camera error"
  lib/pages/homePage.dart
  pubspec.lock
  pubspec.yaml
Labels: hactoberfest-accepted

#19 Added Return A Book
  android/app/src/main/AndroidManifest.xml
  assets/images/Group 2.png
  assets/images/done.png
  lib/models/Book_model.dart
  lib/pages/addNewBookPage.dart
  lib/pages/homePage.dart
  lib/pages/returnBookPage.dart
  lib/pages/splashScreen.dart
  pubspec.lock
  pubspec.yaml
Labels: hactoberfest-accepted

#21 Rohan
  lib/pages/splashScreen.dart
Labels: hacktoberfest-accepted, hactoberfest-accepted

#25 [WIP] Added Issue book Page
  .gitignore
  assets/logo.png
  assets/roboto1.ttf
  assets/roboto2.ttf
  assets/roboto3.ttf
  lib/invoice.dart
  lib/main.dart
  lib/models/Book_model.dart
  lib/pages/addNewBookPage.dart
  lib/pages/homePage.dart
  lib/pages/issueBookPage.dart
  lib/viewpdf.dart
  pubspec.lock
  pubspec.yaml
Labels: hacktoberfest-accepted

#30 Added Issue book Page
  .gitignore
  assets/logo.png
  assets/roboto1.ttf
  assets/roboto2.ttf
  assets/roboto3.ttf
  lib/invoice.dart
  lib/main.dart
  lib/models/Book_model.dart
  lib/pages/addNewBookPage.dart
  lib/pages/homePage.dart
  lib/pages/issueBookPage.dart
  lib/viewpdf.dart
  pubspec.lock
  pubspec.yaml
Labels: hacktoberfest-accepted
